### ISSUE TITLE
Function generate_unshifted_mask returns wrong value

### ISSUE THREAD

**Issue by UrbanVibes** [kensmith/cppmmio#2]
I was not allowed to commit a branch to the repo in order to make a pull request, so I'll describe the problem and proposed fix here.
The function is in the file: cppmmio/examples/3-redux/generate_mask.hpp

* The recursive call in generate_unshifted_mask sets the same bit in the recursion result, this can be fixed by left shifting before setting the lowest bit.
* The expressions in the ternary operator seems to be the opposite of what they are supposed to be, they should switch place.

The naughty code:
 return width ? 0 : 1 | generate_unshifted_mask(width - 1);

The proposed fix
 return width ? 1 | generate_unshifted_mask(width - 1) << 1 : 0;

Bonus question: Would this still be your preferred method for register access or have you seen a even brighter light since 2014?

**Comment by micromouseonline** [comment]
I also found that the masks were not generated at compile time unless they were separately generated as constexpr inside the read and write methods. Thus the template in reg_t.hpp shoule be:

````
template <typename mut_t, uint32_t addr, int offset, int width>
struct reg_t {
    static_assert(width > 0, "nonpositive width");
    static_assert(offset >= 0, "negative offset");
    static_assert(width + offset <= std::numeric_limits<uint32_t>::digits, "width overflow");

    static uint32_t read() {
        constexpr uint32_t mask = generate_mask(offset, width);
        return mut_t::read(reinterpret_cast<volatile uint32_t*>(addr), offset, mask);
    }

    static void write(uint32_t val) {
        constexpr uint32_t mask = generate_mask(offset, width);
        mut_t::write(reinterpret_cast<volatile uint32_t*>(addr), offset, mask, val);
    }
};
````

**Comment by kensmith** [comment]
I didn't notice your helpful feedback until this week, @UrbanVibes and @micromouseonline. My apologies.

@UrbanVibes, right you are. I proved your correctness in an ad hoc unit test and merged in your fix.

@micromouseonline, I must not have noticed this or perhaps back when I built this for the CppCon talk, compilers behaved differently. At any rate your fix does not change the semantics so if it works for you, I'm all for it.

@UrbanVibes to answer your bonus question, if I had to do MMIO for a real project, I would have to do some looking around at the state of the art. I still think compile time constraint enforcement is worth the compile time increase tradeoff due to increased safety. But there may have been new thinking that's come along since then. In 2016, I became a manager and in 2022, I left the industry to take a sabbatical so my opinion today is probably less valuable than it was in 2014 tbh. Follow your instincts. You'll make good choices.
